# Generated by Django 4.2.11 on 2026-02-25 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('contribution', 'Contribution'), ('loan_apply', 'Loan Application'), ('loan_approve', 'Loan Approval'), ('loan_reject', 'Loan Rejection'), ('loan_disburse', 'Loan Disbursement'), ('repayment', 'Repayment'), ('withdrawal', 'Withdrawal'), ('profile_update', 'Profile Update')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chamaprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamaprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamaprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chamaprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='chamaprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamaprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='chamaprofile',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamaprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: 254712345678 or 0712345678', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: 254712345678 or 0712345678', regex='^(254|0)[0-9]{9}$')]),
        ),
        migrations.AddIndex(
            model_name='chamaprofile',
            index=models.Index(fields=['role'], name='core_chamap_role_ba853c_idx'),
        ),
        migrations.AddIndex(
            model_name='chamaprofile',
            index=models.Index(fields=['phone_number'], name='core_chamap_phone_n_acc679_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member', 'status'], name='core_contri_member__95686d_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['payhero_reference'], name='core_contri_payhero_7e7c74_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member', 'status'], name='core_loan_member__7c9dea_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['approved', 'disbursed'], name='core_loan_approve_d99ede_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['loan', 'status'], name='core_repaym_loan_id_456542_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['payhero_reference'], name='core_repaym_payhero_a28ede_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['member', 'status'], name='core_withdr_member__aded5c_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['payhero_reference'], name='core_withdr_payhero_c4b5bf_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx'),
        ),
    ]
