# Generated by Django 6.0.2 on 2026-02-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_chamaprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='stellar_recorded_at',
            field=models.DateTimeField(blank=True, help_text='When this transaction was recorded on the Stellar blockchain', null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='stellar_tx_hash',
            field=models.CharField(blank=True, help_text='Stellar transaction hash', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='stellar_recorded_at',
            field=models.DateTimeField(blank=True, help_text='When this transaction was recorded on the Stellar blockchain', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='stellar_tx_hash',
            field=models.CharField(blank=True, help_text='Stellar transaction hash', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='stellar_recorded_at',
            field=models.DateTimeField(blank=True, help_text='When this transaction was recorded on the Stellar blockchain', null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='stellar_tx_hash',
            field=models.CharField(blank=True, help_text='Stellar transaction hash', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='stellar_recorded_at',
            field=models.DateTimeField(blank=True, help_text='When this transaction was recorded on the Stellar blockchain', null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='stellar_tx_hash',
            field=models.CharField(blank=True, help_text='Stellar transaction hash', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('contribution', 'Contribution'), ('loan_apply', 'Loan Application'), ('loan_approve', 'Loan Approval'), ('loan_reject', 'Loan Rejection'), ('loan_disburse', 'Loan Disbursement'), ('repayment', 'Repayment'), ('withdrawal', 'Withdrawal'), ('profile_update', 'Profile Update'), ('stellar_record', 'Stellar Blockchain Record')], max_length=50),
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('contribution', 'Contribution'), ('loan_disbursement', 'Loan Disbursement'), ('repayment', 'Repayment'), ('withdrawal', 'Withdrawal')], help_text='Which type of chama transaction this represents', max_length=20)),
                ('reference_id', models.PositiveIntegerField(help_text='Primary key of the source record (Contribution, Loan, etc.)')),
                ('stellar_tx_hash', models.CharField(help_text='Stellar blockchain transaction hash — globally unique', max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KSh at time of recording', max_digits=10)),
                ('memo', models.CharField(blank=True, help_text='Memo recorded on Stellar (e.g. CONTRIB:42:5000)', max_length=28)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this log entry was created locally')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the transaction was confirmed on Stellar', null=True)),
                ('member', models.ForeignKey(help_text='Member who owns the underlying transaction', on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_txs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'reference_id'], name='core_blockc_transac_b2161c_idx'), models.Index(fields=['stellar_tx_hash'], name='core_blockc_stellar_8f2da2_idx'), models.Index(fields=['member', '-created_at'], name='core_blockc_member__5fee1a_idx')],
            },
        ),
    ]
