# Generated by Django 6.0.2 on 2026-03-28 16:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contribution_stellar_recorded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_txs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='memo',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='reference_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='stellar_tx_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='transaction_type',
            field=models.CharField(choices=[('contribution', 'Contribution'), ('loan_disbursement', 'Loan Disbursement'), ('repayment', 'Repayment'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chamaprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: 254712345678 or 0712345678', regex='^(254|0)[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='stellar_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='stellar_tx_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_period_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='stellar_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='stellar_tx_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='stellar_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='stellar_tx_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='stellar_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='stellar_tx_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
